---
- hosts: localhost

  vars_files:
    - vars/common.yml
    - vars/dwarf.yml

  roles:
    - { role: docker, become: yes }

  pre_tasks:
    - name: Mount partitions
      become: yes
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.opts }}"
        state: "{{ item.state }}"
      with_items: "{{ mountpoints }}"
      loop_control:
        label: "{{ item.path }}"

- hosts: localhost

  vars_files:
    - vars/common.yml

  roles:
    - { role: ssh, become: yes }

  tasks:
    - name: Global Git configuration
      git_config:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        scope: global
      with_dict: "{{ git_config }}"

    - block:
      - name: Set timezone
        timezone:
          name: "{{ tz }}"

      - name: Install packages
        package:
          name: "{{ item }}"
          state: present
        with_items:
          - nano
          - ncdu
          - htop
          - git
          - mc

      - name: Install Rmate
        get_url:
          url: https://raw.github.com/aurora/rmate/master/rmate
          dest: /usr/local/bin/sublime
          owner: root
          group: root
          mode: "u=rwx,g=rx,o=rx"

      become: yes