---
- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- import_tasks: secure-ssh.yml
- import_tasks: sudo.yml
- import_tasks: zsh.yml