---
- name: Ensure old versions of Docker are not installed
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-docker

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
- name: Install Docker
  apt: name=docker-ce

- name: Ensure Docker is started and enabled at boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes