---
- name: Install Docker
  import_tasks: install.yaml

- name: Set up containers
  import_tasks: containers.yaml

- name: Install camera prune service and timer
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '{{ item.mode }}'
  with_items:
    - src: prune.j2.service
      dest: /etc/systemd/system/camera-prune.service
      owner: root
      group: root
      mode: 0644
    - src: prune.j2.timer
      dest: /etc/systemd/system/camera-prune.timer
      owner: root
      group: root
      mode: 0644

- name: Enable camera prune timer
  systemd:
    name: camera-prune.timer
    state: started
    enabled: yes