---
- name: Get architecture
  shell: dpkg --print-architecture
  register: architecture

- name: Ensure old versions of Docker are not installed
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Ensure dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - python-docker

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- apt_repository:
    state: present
    repo: deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_channel }}

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    